blog/urls.py
from django.urls import path
from blog.views import *

#create requests here

app_name='blog'

urlpatterns=[
    path('',bloghome,name='bloghome'),
    path('post/<int:id>',post,name='post'),
    path('postlike/<int:id>',post_likes,name='postlike'),
    path('about',about,name='about'),
    path('contact',contact,name='contact'),
    path('dashboard',dashboard,name='dashboard'),
    path('user_login',user_login,name='login'),
    path('user_signup',user_signup,name='signup'),
    path('user_logout',user_logout,name='logout'),
    path('newpost',newpost,name='newpost'),
    path('updatepost/<int:id>',updatepost,name='updatepost'),
    path('deletepost/<int:id>',deletepost,name='deletepost'),
    path('setsess',setsess,name='setsess'),
    path('getsess',getsess,name='getsess'),
    path('delsess',delsess,name='delsess'),
]

proj1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import render

def index(request):
    return render(request,'crudfv/index.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('crudfv/',include('crudfv.urls',namespace='crudfv')),
    path('crudcbv/',include('crudcbv.urls',namespace='crudcbv')),
    path('blog/',include('blog.urls',namespace='blog')),
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
 urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    desc = models.TextField(max_length=200)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='users')
    views = models.IntegerField(default=0)
    answers= models.IntegerField(default=0)
    likes= models.IntegerField(default=0)
    view_status= models.BooleanField(default=False)
    like_status=models.BooleanField(default=False)
    post_image=models.ImageField(upload_to='upload/images')

    def __str__(self):
        return str(self.id)

def generate_comment_id():
    last_comment_id=Comments.objects.all().order_by('cmnt_id').last().cmnt_id
    if last_comment_id:
        return last_comment_id + 1
    return 1001


class Comments(models.Model):
    cmnt_id=models.IntegerField(primary_key=True,default=generate_comment_id)
    comment =models.TextField(max_length=500)
    pid=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')

    def __str__(self):
        return str(self.cmnt_id)


# class Answer(models.Model):
#     pass

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from blog.models import Post
from django.contrib.auth.forms import (UserCreationForm,
                                       UserChangeForm,
                                       AuthenticationForm,
                                       UsernameField)
# from django.utils.translation import gettext,gettext_lazy as_
#create your application forms here

class UserSignupForm(UserCreationForm):
    password1=forms.CharField(label='Re-Type password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Re-Type password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {'username':'User Name','first_name':'First Name','last_name':'Last Name','email':'Email'}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'password1':forms.PasswordInput(attrs={'class':'form-control'}),
            'password2':forms.PasswordInput(attrs={'class':'form-control'}),
        }


class UserLoginForm(AuthenticationForm):
   username=UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'})),
   password=forms.CharField(label='(Password)',strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class UserProfileForm(UserChangeForm):
    password1 = None
    date_joined = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type':'datetime-local'}))
    last_login = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type':'datetime-local'}))
    class Meta:
        model =  User
        fields =  ['username','first_name','last_name','email','date_joined','last_login']
        labels = {'email':'Email Address','first_name':'First Name'}

class AdminProfileForm(UserChangeForm):
    password1 = None
    date_joined = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type':'datetime-local'})) 
    last_joined = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type':'datetime-local'})) 
    class Meta:
        model =User
        # fields =  '__all__'
        labels = {'email':'Email'}
        exclude=['password']

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['id','title','desc','post_image']
        labels = {'title':'Title','desc':'Description','post_image':'Add Image'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'}),
            }

blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from blog.forms import UserSignupForm,UserLoginForm,NewPostForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from blog.models import Post
from django.contrib.auth.models import Group
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

# class PostDetailView(DetailView,LoginRequiredMixin):
#     model = Post
#     context_object_name ='posts'
#     template_name ='blog/post.html'
#     login_url ='blog/login'

def bloghome(request):
    posts = Post.objects.all()
    context = {'msg':'Pystack Blog Development','posts':posts}
    return render(request,'blog/home.html',context)

def post(request,id):
    post = Post.objects.get(pk=id)
    viewed_posts = request.session.get('viewed_posts',[])
    print(viewed_posts)
    if id not in viewed_posts:
        post.views = post.views + 1
        post.save()
        viewed_posts.append(id)
        print(viewed_posts)
        request.session['viewed_posts'] = viewed_posts
    context = {'msg':'This is User Post Page','post':post}
    return render(request,'blog/post.html',context)

def post_likes(request,id):
    post = Post.objects.get(pk=id)
    liked_posts = request.session.get('liked_posts',[])
    if id not in liked_posts:
        post.likes = post.likes + 1
        post.save()
        liked_posts.append(id)
        request.session['liked_posts'] = liked_posts
    context = {'msg':'This is User Post Page','post':post}
    return render(request,'blog/post.html',context)

def about(request):
    return render(request,'blog/about.html')

def contact(request):
    return render(request,'blog/contact.html')

def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.filter(author=request.user)
        user = request.user
        fullname = user.get_full_name()
        groups = Group.objects.all()
        return render(request,'blog/dashboard.html',{'posts':posts,'fullname':fullname,'groups':groups})
    else:
        return HttpResponseRedirect('/blog/user_login')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserLoginForm(request=request,data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                pwd = form.cleaned_data['password']
                user = authenticate(username=uname,password=pwd)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Login Done Successfully!!')
                    return HttpResponseRedirect('/blog/dashboard')
        else:
            form = UserLoginForm()
        context = {'form':form}
        return render(request,'blog/login.html',context)
    else:
        return HttpResponseRedirect('/blog/dashboard')

def user_signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='Author')
            user.groups.add(group)
            messages.success(request,'Singup Done as Author Suucessfully!!')
    else:
        form = UserSignupForm()
    context = {'form':form}
    return render(request,'blog/signup.html',context)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/blog/user_login')

def newpost(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = NewPostForm(request.POST,request.FILES)
            if form.is_valid():
                title = form.cleaned_data['title']
                desc = form.cleaned_data['desc']
                post_image = form.cleaned_data['post_image']
                author = request.user
                post1 = Post(title=title,desc=desc,author=author,post_image=post_image)
                post1.save()
                form = NewPostForm()
        else:
            form = NewPostForm()
        return render(request,'blog/newpost.html',{'form':form})
    else:
        return HttpResponseRedirect('/blog/user_login')
    
def updatepost(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            post = Post.objects.get(pk=id)
            form = NewPostForm(request.POST,instance=post)
            if form.is_valid():
                form.save()
                messages.success(request,'Post Updated')
                return HttpResponseRedirect('/blog/dashboard')
        else:
            post = Post.objects.get(pk=id)
            form = NewPostForm(instance=post)
        context = {'form':form}
        return render(request,'blog/updatepost.html',context)
    else:
        return HttpResponseRedirect('/blog/user_login')
    
def deletepost(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            post = Post.objects.get(pk=id)
            post.delete()
            return HttpResponseRedirect('/blog/dashboard')
    else:
        return HttpResponseRedirect('/blog/user_login')
    

def setsess(request):
    request.session['sid'] = 1005
    request.session['sname'] = 'Gopi'
    request.session['course'] = 'python'
    request.session.setdefault('fee',12000)
    request.session.set_expiry(60)
    return render(request,'blog/sess.html')

def getsess(request):
    sid = request.session.get('sid')
    sname = request.session.get('sname')
    # keys = request.session.keys()
    # values = request.session.values()
    # items = request.session.items()
    return render(request,'blog/sess.html',{'sid':sid,'sname':sname})

def delsess(request):
    # if 'sid' in request.session:
    #     del request.session['sid']
    request.session.flush()
    request.session.clear_expired()
    return render(request,'blog/sess.html')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class="col-sm-10">
        <h3 class="text-white my-3">ABOUT PAGE</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Culpa vel unde consectetur nemo necessitatibus eum nesciunt blanditiis quaerat, 
            distinctio repellendus, earum laboriosam tempore esse, accusantium voluptatibus 
            ipsa est? Beatae rem nostrum quidem eum, temporibus hic error voluptas rerum nesciunt, 
            eius explicabo architecto assumenda, corrupti at!
        </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, 
            corporis sint assumenda tempore molestiae iste corrupti facere sit alias, 
            eius consequatur minus amet deleniti veniam eum voluptate iusto numquam doloremque
             beatae ipsa? Error commodi labore, praesentium ipsa excepturi quas animi 
            suscipit corrupti odit aliquam porro.</p>
    </div>
{% endblock main %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
    <title>Blog:Home</title>
</head>
<body>
    <div class="container-fluid bg-dark text-center ">
        {% include 'blog/navbar.html' %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg%}{% endblock msg %}
            </div>
            <div class="row">
                {% block left%}{% endblock left %}
                {% block main%}{% endblock main %}
            </div>
        </div>
    </div>
</body>
<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/popper.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.js' %}"></script>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class="col-sm-10">
        <h3 class="text-white my-3">CONTACT PAGE</h3>
        <form action="" method="post">
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" required>
              </div>
              <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email" required>
              </div>
              <div class="mb-3">
                <label for="phone" class="form-label">Phone</label>
                <input type="tel" class="form-control" id="phone" name="phone" required>
              </div>
              <div class="mb-3">
                <label for="message" class="form-label">Message</label>
                <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock main %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class="col-sm-12">
            <div>
                <h3 class="text-center alert alert-info mt-3">All Posts</h3>
                <h4>
                <a href="{% url 'blog:newpost' %}" class="btn btn-success">New Post</a>
                    {% for group in groups %}
                        {{group.name}}
                    {% endfor  %}
                </h4>
            </div>
                {% if posts %}
                    <table class="table table-hover bg-white">
                        <thead>
                            <tr class="text-center">
                                <th scope="col" style="width:3%;"></th>
                                <th scope="col" style="width:3%;">PostID</th>
                                <th scope="col" style="width:27%;">Title</th>
                                <th scope="col" style="width:50%;">Description</th>
                                <th scope="col" style="width:20%;">Actions</th>
                            </tr>
                        </thead> 
                        <tbody>
                            {% for post in posts %}
                                <tr>
                                    <td scope="row">
                                        <span class="badge rounded-pill bg-primary">Views:{{post.views}}</span>
                                        <span class="badge rounded-pill bg-primary">Answers:0</span>
                                        <span class="badge rounded-pill bg-primary">Likes:{{post.likes}}</span>
                                    </td>
                                    <th scope="row">{{post.id}}</th>
                                    <td>{{post.title}}</td>
                                    <td>{{post.desc}}</td>                                     </td>
                                    <td class="text-center">
                                        <a href="{% url 'blog:updatepost' post.id %}" class="btn btn-warning btn-sm">Update</a>
                                        {% if perms.blog.delete_post %}
                                        <form action="{% url 'blog:deletepost' post.id %}" method="post" novalidate class="d-inline">
                                            {% csrf_token %}
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        </form>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% empty %}
                                <h4 class="text-center alert alert-warning"></h4>
                            {% endfor %}
                        </tbody>

                    </table>
                    {% endif %}

        </h1>
    </div>
{% endblock main %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class="col-sm-12">
        <h3 class="text-white my-3 text-center">POSTS</h3>
        
        {% if posts %}
        <table class="table table-hover bg-white">
            <thead>
                <tr class="text-center">
                    <th scope="col" style="width:3%;"></th>
                    <th scope="col" style="width:10%;"></th>
                    <th scope="col" style="width:35%;"></th>
                </tr>
            </thead> 
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td scope="row">
                            <span class="badge rounded-pill bg-primary">Views:{{post.views}}</span>
                            <span class="badge rounded-pill bg-primary">Answers:0</span>
                            <span class="badge rounded-pill bg-primary">Likes:{{post.Likes}}</span>
                        </td>
                        <th scope="row">{{post.id}}
                            <img width="200" height="100" src="{{post.post_image.url}}" alt="" srcset="">{{post.post_image.url}}
                        </th>
                        <td><a href="{% url 'blog:post' post.id %}">{{post.title}} </a></td>
                        <td>{{post.desc}} <br>
                            <a href="">{{post.author|title}}</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="">Answer</a>
                        </td>                             
                    </tr>
                    {% empty %}
                    <h4 class="text-center alert alert-warning"></h4>
                {% endfor %}
            </tbody>

        </table>
        {% endif %}
    </div>
{% endblock main %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class=" col-sm-12">
        <h3 class="text-white my-3 text-center">User Login Page</h3>
        <style>
            .success{
                color: green;
            }
        </style>
        <div class="row justify-content-center g-5">
            <form method="post" novalidate class="col-sm-8 row g-2">
                {% csrf_token %}
                {% for field in form %}
                    {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
                {% endfor  %}
                <input type="submit" value="Login" class="btn btn-primary mb-3">
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        {{error}}
                    {% endfor %}
                {% endif %}
            </form>
            {% if messages %}
                {% for message in messages %}
                    <h3 
                        {% if message.tags %} 
                            class="{{message.tags}}" 
                        {% endif %}
                    >{{message}}</h3>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock main %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:bloghome' %}">MyBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:about'%}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:dashboard'%}">Dashboard</a>
          </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:signup' %}">Signup</a>
            </li>
            {% else %}
            <li class="nav-item">
              {% if user %}
                <a href="" class="nav-link">{{user}}</a>
              {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>
      </div>
    </div>
  </nav>

blog/templates/blog/newpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %} 
    <div class="col-sm-10">
        <h3 class="text-white my-3">New Post</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="btn btn-success">
            <a href="{% url 'blog:dashboard' %}" class="btn btn-danger">Cancel</a>
        </form>
    </div>
{% endblock main%}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class="col-sm-12">
        <h3 class="text-white my-3 text-center">USER POSTS</h3>
        <h2>{{post.title}}</h2> <br>
        <p>{{post.desc}}</p>
        <div class="row">
            <div class="col-auto">
                <h6>Views:<span class="badge text-bg-secondary">{{post.views}}</span></h6>
            </div>
            <div class="col-auto">
                <a class="btn btn-primary btn-sm" href="{% url 'blog:postlike' post.id %}">Likes <span>{{post.likes}}</span></a>
            </div>
        </div>
        <div class="row text-right ml-5">
            <div class="col-ms-auto">
                {% for comment in post.comments.all %}
                    <h3>{{comment.comment}}</h3> <br>
                {% empty %}
                    <h4>No Comments</h4>
                {% endfor %}

            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <form action="" method="post">
                    <label for="">Comment</label> <br>
                    <textarea name="" id="" cols="90" rows="5"></textarea> <br><br>
                    <input type="submit" value="Post Your Comment" class="btn btn-primary btn-md">
                </form>
            </div>
        </div>
    </div>
{% endblock main %}

blog/templates/blog/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<style>
    .success{
        color: rgb(255, 55, 0);
    }
    .errors{
        color: darkblue;
    }
    .backbtn{
            /* display: inline-block; */
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            border: 2px solid transparent;
            /* transition: all 0.3s ease; */
        }
</style>
<body>
    <h1>Welcome to Profile : {{username}}</h1>
    <a href="{% url 'blog:myprofile' %}">My Profile</a>
    <a href="{% url 'blog:logout' %}">Logout</a>
    <a href="{% url 'blog:changepwd1' %}">Change PassWord</a>
    <a href="{% url 'blog:changepwd2' %}">Forgot PassWord</a>
    <a href="{% url 'blog:dashboard' %}">DashBoard</a>


    {% if users %}
        {% for user in users %}
            <a href="{% url 'blog:userinfo' user.id %}" >{{user.username}}</a>
        {%endfor%}
    {% endif %}
    {% if form %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        {{field.label_tag}} {{field}} {{field.errors|striptags}}<br><br>
        {% endfor %}
        <!-- {{form.as_p}} -->
        <input type="submit" value="Submit">
        <a href="{% url 'blog:profile' %}"  class="backbtn">Back</a>
    </form>
    {% endif %}
    {% if messages %}
        {% for message in messages %}
            <h3 {% if message.tags %} class="{{message.tags}}" {% endif %} >{{message}}</h3>
        {% endfor %}
    {% endif %}
</body>
</html>

blog/templates/blog/sess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>session data</title>
</head>
<body>
    <h1>Session variable data: {{sid}} | {{sname}} </h1>
    {% for i in request.session.items %}
        <h2>{{i}}</h2>
    {% endfor%}
    {{request.session.get_session_cookie_age}} <br>
    {{request.session.get_expiry_age}} <br>
    {{request.session.get_expiry_date}} <br>
    {{request.session.get_expire_at_browser_close}} <br>

</body>
</html>

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <div class=" col-sm-12">
        <h3 class="text-white my-3 text-center">User Registration Page</h3>
        <style>
            .success{
                color: green;
            }
        </style>
        <div class="row justify-content-center g-5">
            {% if messages %}
                {% for message in messages %}
                    <h3 
                        {% if message.tags %} 
                            class="alert alert-{{message.tags}}" 
                        {% endif %}
                    >{{message}}</h3>
                {% endfor %}
            {% endif %}

            <form method="post" novalidate class="col-sm-8 row g-2">
                {% csrf_token %}
                {% for field in form %}
                    {{field.label_tag}} {{field}} {{field.errors|striptags}} <br><br>
                {% endfor  %}
                <input type="submit" value="SignUp" class="btn btn-primary mb-3">
            </form>
        </div>
    </div>
{% endblock main %}

blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %} 
    <div class="col-sm-10">
        <h3 class="text-white my-3">Update Post</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update" class="btn btn-success">
            <a href="{% url 'blog:dashboard' %}" class="btn btn-danger">Cancel</a>
        </form>
    </div>
{% endblock main%}